CREATE OR REPLACE TABLE sec_filings.graph_edges AS

WITH json_data AS (
   SELECT
    company,
    company_name,
    cik,
    sic,
    irs_number,
    state_of_inc,
    org_name,
    sec_file_number,
    film_number,
    business_street_1,
    business_street_2,
    business_city,
    business_state,
    business_zip,
    business_phone,
    mail_street_1,
    mail_street_2,
    mail_city,
    mail_state,
    mail_zip,
    filing_url,
    year,
    section_id,
    -- Extract the text content from the Gemini JSON result
    result as raw_text
   FROM sec_filings.insights
),
parsed_data AS (
  SELECT
    company,
    company_name,
    cik,
    sic,
    irs_number,
    state_of_inc,
    org_name,
    sec_file_number,
    film_number,
    business_street_1,
    business_street_2,
    business_city,
    business_state,
    business_zip,
    business_phone,
    mail_street_1,
    mail_street_2,
    mail_city,
    mail_state,
    mail_zip,
    filing_url,
    year,
    section_id,
    -- Parse the extracted text as JSON. Clean markdown if present just in case.
    SAFE.PARSE_JSON(
      REGEXP_REPLACE(REGEXP_REPLACE(raw_text, '^```json\\n', ''), '\\n```$', '')
    ) as data
  FROM json_data
)

-- 1. Market Edges
SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(market_item, '$.market') AS target_node,
  'Market' AS target_label,
  'ENTERING' AS edge_type,
  JSON_VALUE(market_item, '$.evidence') AS properties,
  JSON_VALUE(market_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.markets.entering')) AS market_item

UNION ALL

SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(market_item, '$.market') AS target_node,
  'Market' AS target_label,
  'EXITING' AS edge_type,
  JSON_VALUE(market_item, '$.evidence') AS properties,
  JSON_VALUE(market_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.markets.exiting')) AS market_item

UNION ALL

SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(market_item, '$.market') AS target_node,
  'Market' AS target_label,
  'EXPANDING' AS edge_type,
  JSON_VALUE(market_item, '$.details') AS properties,
  JSON_VALUE(market_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.markets.expanding')) AS market_item

UNION ALL

-- 2. Risk/Opportunity Edges (Emerging Risks)
SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(risk_item, '$.risk') AS target_node,
  'Risk' AS target_label,
  'FACES_RISK' AS edge_type,
  JSON_VALUE(risk_item, '$.description') AS properties,
  JSON_VALUE(risk_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.risks_opportunities.emerging_risks')) AS risk_item

UNION ALL

-- 2b. Emerging Opportunities (New edge type: PURSUING_OPPORTUNITY)
SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(opp_item, '$.opportunity') AS target_node,
  'Opportunity' AS target_label,
  'PURSUING' AS edge_type,
  JSON_VALUE(opp_item, '$.description') AS properties,
  JSON_VALUE(opp_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.risks_opportunities.emerging_opportunities')) AS opp_item

UNION ALL

-- 3. Competitor Edges
SELECT
  GENERATE_UUID() AS edge_id,
  company AS source_node,
  company_name,
  cik,
  sic,
  irs_number,
  state_of_inc,
  org_name,
  sec_file_number,
  film_number,
  business_street_1,
  business_street_2,
  business_city,
  business_state,
  business_zip,
  business_phone,
  mail_street_1,
  mail_street_2,
  mail_city,
  mail_state,
  mail_zip,
  filing_url,
  year,
  section_id,
  'Company' AS source_label,
  JSON_VALUE(comp_item, '$.name') AS target_node,
  'Competitor' AS target_label,
  'COMPETES_WITH' AS edge_type,
  JSON_VALUE(comp_item, '$.relationship') AS properties,
  JSON_VALUE(comp_item, '$.reference') AS reference
FROM parsed_data,
UNNEST(JSON_QUERY_ARRAY(data, '$.competitors')) AS comp_item;
